add design html home1
st-thangtran2/FE-Internship-2023_Thang-Tran-V_FE-Exercise pull request #5
Opened 2023-08-04 09:08 UTC by st-thangtran2

### Description
design html home1

2023-08-06 03:44 UTC, st-thangtran2 commented
Hi anh @st-quangnguyen2  @st-manhle , em đã fix lại các lỗi mà anh comment, nhờ a review giúp e với, em cảm ơn ạ

2023-08-06 04:17 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +</head>
chỗ `title` này mình để cụ thể tên của trang

2023-08-06 04:23 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      </div>
trong bài tập này thì mình sẽ dùng `h1` để bọc cái logo

2023-08-06 04:28 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      <section class="section-shopnow">
thẻ `section` mặc định nó sẽ có một class `section` sau đó là một class định danh nó là `section` gì
Vd: `section section-shopnow`
Áp dung tương tự với các `section` còn lại

2023-08-06 04:36 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +        <div class="headline-button">
thẻ `h1` đã được dùng cho logo em dùng thẻ khác để thay thế

2023-08-06 04:42 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +        </ul>
với một cái list thì thường anh sẽ đặt class như thế này:
`{object}-list > {object}-item > {object} > ...`
Áp dụng vào trường hợp này:
```
ul.pill-list
  li.pill-item
    div.pill
      pill-icon
      pill-title
      pill-desc
```
Em đọc bài anh sharing về cách tư duy để rõ hơn phần này.
MÌnh sẽ áp dụng tương tự cho các phần còn lại

2023-08-06 04:46 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +          </li>
`product-list > product-item > product > ...`
`prodcut-text -> product-name` và dùng thẻ `h4`

2023-08-06 04:49 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +        <ul class="features">
`feature-title` -> `section-title`

2023-08-06 04:50 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +          <ul class="list-info">
tại sao lại có `camelCase` trong class vậy em

2023-08-06 04:50 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +        </div>
cái này là một `section` riêng

2023-08-06 04:58 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +          </ul>
Nếu em để ý thì có thể dễ thấy đây là dạng list trong list.
```
ul
  li
    ...
    ul
      li
```
và những nội dung ở đây đều có thể link tới trang khác nên mình dùng `a` thay cho `p`
Kiểm tra hết lại các tên class
anh đang không hiểu các class `{object}-text` nó có ý nghĩa gì
`text` thường chỉ loại dữ liệu, chứ không thể hiện rõ mục đích mà phần nội dung đó đang biểu diễn .
Anh cần nó rõ ràng hơn chỗ này, mình có thể dùng `link, title, name, desc...` tuỳ theo sao cho nó phù hợp

2023-08-06 04:59 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +</html>
đóng cho anh thêm cái `Enter` để thêm dòng mới cuối file. Anh mong đây đây là lần cuối bắt lỗi về vấn đề này nhá.

2023-08-06 05:01 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +        <span class="menu-icon">icon avatar</span>
`span` -> `i`
thêm class dùng để định danh icon, không để text hiển thị tạm

2023-08-06 05:02 UTC, st-quangnguyen2 requested changes
@st-thangtran2 check cmts

2023-08-07 12:33 UTC, st-manhle requested changes
Check cmts
Xem lại description của PR

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +        <a href=""> <img alt="logo" class="logo"></a>
alt của img logo cần giống title của trang web vì lý do seo

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +      </nav>
đặt tên menu chung chung quá e nha
gợi ý `.nav-menu`

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +      <div class="header-action">
`header-actions`, chú ý số nhiều, số ít

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +          <a class="section-action">SHOP NOW</a>
Nếu code như này là click vào icon sẽ k có action, update lại nha
section-action sẽ hay hơn là section-button nha

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +      </section>
a nghĩ phần này là 1 block nhỏ trong section-banner nha, k cần phải tạo 1 section riêng

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +  <div class="container">
container nằm trong header, không nằm ngoài nha

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +    </header>
section banner thuộc main chứ không phải header nha

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +          <img class="product-image" alt="anh san pham">
alt của hình product thì tốt nhất nên đặt = tên product nha

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +        </li>
thiếu thẻ a để navigate sang product detail page

2023-08-07 12:33 UTC, st-manhle commented on html-exercise/index.html
> +            <ul class="icon-list">
icon-list không có ý nghĩa, nên đổi thành social-list

2023-08-08 04:42 UTC, st-quangnguyen2 approved these changes

2023-08-08 04:42 UTC, merged